### ISSUE TITLE
raised typepy.error.TypeConversionError leads to AttributeError: module 'typepy' has no attribute '_error'

### ISSUE THREAD

**Issue by mojeto** [springload/typed_environment_configuration#6]
* Typed Environment Configuration version: 0.1.3
* Python version: 3.8.3
* Operating System: alpine linux

### Description

Invalid incoming value that raises `TypeConversionError` triggers another `AttributeError: module 'typepy' has no attribute '_error'` exception

### What I Did

```
DJANGO_DEBUG=1 python ./manage.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/typed_environment_configuration/typed_environment_configuration.py", line 32, in getenv
    return self._value_type(value, strict_level=self._strict_level).convert()
  File "/usr/local/lib/python3.8/site-packages/typepy/type/_base.py", line 120, in convert
    raise TypeConversionError(
typepy.error.TypeConversionError: failed to convert from str to BOOL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/app/settings/__init__.py", line 39, in <module>
    fill(_DJANGO_ENVVARS, vars(), "DJANGO_")
  File "/app/app/settings/__init__.py", line 34, in fill
    v[var.name] = var.getenv(prefix=prefix)
  File "/usr/local/lib/python3.8/site-packages/typed_environment_configuration/typed_environment_configuration.py", line 33, in getenv
    except typepy._error.TypeConversionError:
AttributeError: module 'typepy' has no attribute '_error'
```

**Comment by haydngreatnews** [comment]
Note, #10 would correct this issue

**Comment by PeterDekkers** [comment]
#10 was merged, so this is quite likely resolved now.
